print(10/3)
print(10%3)
print("'navin'")
print('navin')
print("navin's laptop")
print('navin "laptop"')
print('navin\'s "laptop"')
print(10*'navin\n')
# print('c:\docs\navin')
print('c:\docs\\\\\\navin')
print(r'c:\docs\\navin')
print("r"r'c:\docs\\navin')
